name: lumina
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  # State Management & Architecture
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Navigation
  go_router: ^17.1.0
  
  # Storage
  shared_preferences: ^2.5.3
  
  # UI & Animations
  rive: ^0.14.3
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
  # Journal & Rich Text
  flutter_quill: ^11.4.2
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  pdf: ^3.11.3
  printing: ^5.14.2
  widgets_to_image: ^2.0.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  firebase_messaging: ^16.0.0
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true
